import type { Metadata } from 'next'

import Navbar from '@/components/navbar'
import ScreenSize from '@/components/screen-size'

export const metadata: Metadata = {
  title: 'Shopicus Ecommerce Store',
  description: 'Generated by create next app',
}

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Navbar />
      <main className="flex-1 py-10">{children}</main>
      <ScreenSize />
    </>
  )
}
