import type { Metadata } from 'next'
import { Geist } from 'next/font/google'

import Navbar from '@/components/navbar'
import ScreenSize from '@/components/screen-size'
import { ReactQueryProvider } from '@/providers'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Shopicus Ecommerce Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} min-h-dvh bg-slate-950 text-white antialiased`}>
        <ReactQueryProvider>
          <Navbar />
          <main className="">{children}</main>
          <ScreenSize />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
