import type { Metadata } from 'next'

import AdminGuard from '@/layouts/admin-guard'

import { AdminSidebar } from './_components'

export const metadata: Metadata = {
  title: 'Admin Pages',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AdminGuard>
      <div className="grid flex-1 grid-cols-[260px_1fr]">
        <AdminSidebar />
        <div className="flex flex-col px-10 py-4">{children}</div>
      </div>
    </AdminGuard>
  )
}
